### ISSUE TITLE
9주차 팀별과제 checklist

### ISSUE THREAD

**Issue by Hong-YeJi** [lcy061/Mini-project#5]
**9주차 팀별과제 checklist**

- [x] Repository 생성 : 모두 Github에 본인 Repository를 각각 새로 생성(public)하여 구글시트에 본인 Repo URL작성
- [x] 팀원 간 서로 repository를 fork 하고, forked repository에서 pull request 연습(파일 하나씩 추가해서 서로 소개하기)
- [x] 팀원 서로 의논하여 팀 프로젝트 개발 Repo 생성 및 링크 공유
- [x] github issue 개설 : 필요할 때마다 issue를 새로 생성하여 개발에 대한 의논
- [x] 주제선정 및 위키정리 : github issue를 사용하여 CRUD Mini project 를 진행할 주제 선정 및 역할 분담
- [x] 설계 : CRUD 기능, 데이터 파일 저장/읽어오기, 검색 등 메뉴(종료메뉴 제외) 등 10개 이상 함수 정의(구조체도 정의), 깃허브 이슈를 통한 충분한 토론 후 정의
- [x] Github Repo에 README.md 파일 작성(팀원이 적절하게 나누어서 작성후 모아서 각자 README.md 파일에 작성)
