### ISSUE TITLE
10주차 팀별과제 checklist

### ISSUE THREAD

**Issue by Hong-YeJi** [lcy061/Mini-project#8]
**10주차 팀별과제 checklist**

- [x] 검색 기능 및 파일 저장, 읽어보기 기능을 제외한 모든 함수 구현 및 git으로 버전 관리
- [x] 완성된 각 함수를 실행한 화면캡처 업로드 (github repository root에서 /screenshots 폴더 만들어서 이미지 업로드)
- [x] issue를 사용하여 개발에 필요한 의견 교환
- [x] WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가) 

[협업 평가]
mini project의 설계 및 그에 따른 전체적인 완성도 평가
Repository PR과 소유자 PR Merge내역
[WIKI로 개발 자료 정리]
- [x] mini project 주제 및 설명
- [x] 각 함수 담당자 및 개발일정
- [x] 각 함수의 기능에 대한 간단한 설명
(그외 필요한 정보들)
- [x] issue를 사용하여 개발을 위한 의견 교환
